config/routes.rb
RailsApp::Application.routes.draw do

  post "usercfg/savecfg"
  get "usercfg/loadcfg"
  get "password_resets/new"
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create", :as => "login"
  get "signup" => "ranks#new", :as => "signup"
  post "signup" => "ranks#create", :as => "signup"
  post "check" => "ranks#check", :as => "check"
  get "index" => "ranks#index", :as => "index"
  get "admin" => "admin#show", :as => "admin"
  post "onlineusr" => "onlineusr#getlist", :as => "onlineusr"
  root :to => 'ranks#index'
  resources :admin
  resources :session
  resources :password_resets
  resources :ranks

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def new
		
	end
	# POST
	def create
		user = Rank.authenticate(params[:usrname], params[:passwd])
		if user
			session[:user_id] = user.id
			redirect_to root_url, :notice => "Logged in!"
			# flash.now.alert = "Invalid usrname or password"
		else
			flash.now.alert = "Invalid usrname or password"
			render "new"
		end

=begin
		user = Rank.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			if params[:remember_me]
				cookies.permanent[:auth_token] = user.auth_token
			else
				cookies[:auth_token] = user.auth_token
			end
			redirect_to root_url, :notice => "Logged in!"
		else
			flash.now.alert = "Invalid email or password"
			render "new"
		end
=end

	end

	def destroy
		session[:user_id] = nil	
		cookies.delete(:auth_token)
		redirect_to root_url, :notice => "Logged out!"
	end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
<center>
  <h1>登入 </h1>
  <%= form_tag :method => :post  do %>
  <fieldset>
      <%= label_tag :用户名 %>
    <p>
      <%= text_field_tag :usrname, params[:usrname] %>
    </p>
      <%= label_tag :密码 %>
    <p>
      <%= password_field_tag :passwd %>
    </p>
    <p>
      <!-- <p><%= link_to "forgotten password?", new_password_reset_path %></p> -->
      <%= check_box_tag :remember_me, 1, params[:remember_me] %>
      <%= label_tag :remember_me %>
    </p>
  </fieldset>
  <div class="action"><%= submit_tag "登录" %></div>
  <% end %>

  <p><%= link_to '返回', index_path %></p>
</center>