config/routes.rb
RailsApp::Application.routes.draw do

  post "usercfg/savecfg"
  get "usercfg/loadcfg"
  get "password_resets/new"
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create", :as => "login"
  get "signup" => "ranks#new", :as => "signup"
  post "signup" => "ranks#create", :as => "signup"
  post "check" => "ranks#check", :as => "check"
  get "index" => "ranks#index", :as => "index"
  get "admin" => "admin#show", :as => "admin"
  post "onlineusr" => "onlineusr#getlist", :as => "onlineusr"
  root :to => 'ranks#index'
  resources :admin
  resources :session
  resources :password_resets
  resources :ranks

end

app/models/rank.rb
# -*- coding: utf-8 -*-



class Rank < ActiveRecord::Base
	has_many :sudodbs
	belongs_to :onlinelist
	attr_accessible :usrname, :num, :created_on, :updated_at, :savedsudo
	validates :usrname,  :presence => true,  
	:uniqueness => true,  	
	:length => {:minimum => 3, :maximum => 12}  

	validates :email, :presence => true,   
	:length => {:minimum => 4, :maximum => 254},  
	:uniqueness => true,  
	:format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}  

	# validates :passwd, :presence => true,   
	# :length => {:minimum => 4, :maximum => 20}

	attr_accessible :email, :passwd, :passwd_confirmation

	attr_accessor  :passwd
	before_save :encrypt_password, :modifycounts
	validates_confirmation_of :passwd
	validates_presence_of :passwd, :on => :create
	# validates_presence_of :email
	# validates_uniqueness_of :email
	#login
	def self.authenticate(usrname, passwd)
		user = where(:usrname => usrname).first
		if user && user.password_hash == BCrypt::Engine.hash_secret(passwd, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if passwd.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(passwd, password_salt)
		end
	end

	def modifycounts
		#can't be size
		if not self.sudodbs.blank?
			if self.id.nil?
				self.num = 0
			else
				self.num = self.sudodbs.count
			end
		else
			self.num = 0
		end
	end
	#:format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}  
	# def self.authenticate_safely_simply(usrname, passwd)
	# 	where(:usrname => usrname, :passwd => passwd).first
	# end

	#
	before_create { generate_token(:auth_token) }

	def send_password_reset
		generate_token(:password_reset_token)
		self.password_reset_sent_at = Time.zone.now
		save!
		UserMailer.password_reset(self).deliver
	end

	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while Rank.exists?(column => self[column])
	end
end

app/controllers/ranks_controller.rb
# -*- coding: utf-8 -*-

class RanksController < ApplicationController
	# GET /ranks
	# GET /ranks.json
	def index
		@ranks = Rank.order("num desc").limit(50)

		@sudo_today = Sudodb.sudo_today_solved
		@usr_active_week = Sudodb.active_usrs
		@sudolatest = Sudodb.sudo_new

		session[:sudoid] = @sudolatest.id
		
		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @ranks }
		end
	end

	# GET /ranks/1
	# GET /ranks/1.json
	def show
		@rank = Rank.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @rank }
		end
	end

	# GET /ranks/new
	# GET /ranks/new.json
	def new
		@rank = Rank.new
		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @rank }
		end
	end

	# GET /ranks/1/edit
	def edit
		@rank = Rank.find(params[:id])
	end


	# POST /ranks
	# POST /ranks.json
	def create 
		if ( params[:rank][:usrname].blank? or params[:rank][:email].blank? or params[:rank][:passwd].blank? or params[:rank][:password_confirmation].blank? )
			flash.now.alert = "usrname  or email can't be empty"
		elsif params[:rank][:passwd]!=params[:rank][:password_confirmation]
			flash.now.alert = "password not same"
		else
			@rank = Rank.new
			@rank.usrname = params[:rank][:usrname]
			@rank.passwd = params[:rank][:passwd]
			@rank.email = params[:rank][:email]
			@rank.num = 0
			if @rank.save
				session[:user_id] = @rank.id
				# 
				respond_to do |format|

					format.html { redirect_to root_url, :notice => "Signed up!" }
					format.json { render json: @rank.errors, status: :unprocessable_entity }
				end
				return
			end
		end
		respond_to do |format|

			format.html { render "new"}
			format.json { render json: @rank.errors, status: :unprocessable_entity }
		end
	end

	# PUT /ranks/1
	# PUT /ranks/1.json
	def update
		@rank = Rank.find(params[:id])

		respond_to do |format|
			if @rank.update_attributes(params[:rank])
				format.html { redirect_to @rank, notice: 'Rank was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @rank.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /ranks/1
	# DELETE /ranks/1.json
	def destroy
		@rank = Rank.find(params[:id])
		@rank.destroy

		respond_to do |format|
			format.html { redirect_to ranks_url }
			format.json { head :no_content }
		end
	end
	# POST
	def check
		@msg =  ""
		@sudolinerecv=  params[:sudoall]
		@sudolatest = Sudodb.last
		@sudolatest_shrink = ""
		if @sudolatest
			@sudolatest_shrink = @sudolatest.line.gsub(";","").gsub("0","").gsub(" ","").gsub("\n","")
			if @sudolatest.rank.nil?
				if params[:sudoall]== @sudolatest_shrink
					@usr = Rank.find(session[:user_id])
					if @usr
						# @sudolatest.solvedby = @usr.usrname
						@sudolatest.rank = @usr
						@usr.num += 1
						Rank.transaction  do
							if @sudolatest.save!
								@msg = "<p>我们已经保存了你的新记录</p>"
							else
								@msg ="<strong>Warning</strong>: Saved user message failed in sudoku table"
							end
							if @usr.save!
								@msg += "<p>这是你应得的奖励: <strong>战绩 +1 </strong></p><p>你的个人战绩已经更新了: <strong>"+@usr.usrname+": " + @usr.num.to_s+"</strong></p>"

							else
								@msg += "<strong>Error: </strong>Saving your personal data failed, your data will not change</p>"
							end
						end
					else
						@msg = "<strong>Warning</strong>: no user register message found!session may be expired!!"
					end
				else
					@msg = "<strong>Warning</strong>: your sudoku was not coincidence with the one we give you"
				end
			else
				@msg = "<strong>Warning</strong>: Sorry, this sudoku has been solved by someone else before you done."
			end
		else
			@msg = "<strong>Warning</strong>: no sudoku generated, how you did this?"

		end
		render :layout => false

	end

	#private

	def is_authened
		session[:user_id] = @current_user.id
		Rank.find(session[:user_id])
	end

end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/views/ranks/check.html.erb
<%= raw(@msg) %>

<!-- <p><%= @sudolinerecv %></p> -->
<!-- <p><%= @sudolatest_shrink %></p> -->

app/views/ranks/edit.html.erb
<h1>Editing rank</h1>

<%= render 'form' %>

<%= link_to 'Show', @rank %> |
<%= link_to 'Back', ranks_path %>

app/views/ranks/index.html.erb
<div class="append-1 append-2" id="content">
  <center>
    <div class="rewardbox">
      <div class = "error"><strong>:) 厉害，成功解决了一个Sudoku!!</strong></div>
      <% if not current_user %>
      <p> 但是仅注册用户的记录才会保存, 你可以立刻<%= link_to "免费注册", signup_path %>或者<%= link_to "登入", login_path %> </p>
      <% else  %>
      <div class="ajresp"><p>正在检查你的结果 ...</p></div>
      <% end %>
      <%= link_to '继续下一个挑战', index_path %>
    </div>
    <sudobox>
      <table class= "cl_table" border="1" cols="9">
        <tbody>
          <% tbid = 0 %>
          <% for eles in @sudolatest.line.split("\n") %>
          <tr>
            <% for ele in eles.split(" ") %>
            <td id ="<%= 't' + tbid.to_s %>" > 
              <input type="text" id = "<%= 'c' + tbid.to_s %>" size="1" maxlength="1" autocomplete="off" value = <% if ele.to_i==0 then %> "" class = "cell blank" <% else %> "<%= ele %>" readonly  class="cell fixed" <% end %> >
            </td>
            <% tbid +=1 %>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>

    </sudobox>
    <sudobtgroup> 
      <button class="btclear">Clear</button>
    </sudobtgroup>
  </center>
  <div id="disqus_thread"></div>
  <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'dbian';
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
<div id="sidebar">
  <div class="infobox">
    <h3>进度排名</h3>
    <div class="ollist">
      Fetching...
    </div>
  </div>
  <div class="infobox">
    <h3>友情提醒</h3>
    <ol>
      <li>数独更新方式为惰性更新，即当前数独被干掉之后才会生成新的数独</li>
      <li>多人先后解决同一个数独，仅第一位用户得分。<a><strong>未登录用户的游戏结果不会记录</strong></a></li>
      <li>建议使用Chrome, Firedox, IE8+, Safari</li>
    </ol>
  </div>
  
    <div class="infobox" id="recent_usr_bar">
      <h3>本周 MVP</h3>
      <% if @usr_active_week %>
      <% @usr_active_week.each do |sudoz| %>
      <ul>
        <% if (not sudoz.rank.nil?) and (sudoz.sudonum != 0) %>
        <li><%= link_to sudoz.rank.usrname, sudoz.rank %>: <%= sudoz.sudonum %></li>
        <% end %>
      </ul>
      <% end %>

      <% end %>
    </div>
    <div class="infobox" id="rank_bar">
      <h3>Sudokuer Top 50</h3>
      <ol>
        <% @ranks.each do |rank| %>
        <li><%= link_to rank.usrname, rank %> (<%= rank.num %>)</li>
        <% end %>
      </ol>
    </div>
    <div class="infobox" id="sudo_daily_bar">
      <h3>Daily Pushed Sudoku</h3>
      <% if @sudo_today %>
      <% @sudo_today.each do |sudo| %>
      <% if not sudo.rank.nil? %>      
      <ul>
        <li>
          <%= sudo.line.gsub(" ","").gsub("0",".") %>-

          <%= link_to sudo.rank.usrname, sudo.rank %>

        </li>
      </ul>
      <% end %>
      <% end %>
      <% end %>
    </div>
</div>

app/views/ranks/new.html.erb
<center>
  <h1>快速加入Push Suduko</h1>



  <%= form_for :rank do |f| %>
  <fieldset>
    <%= f.label "昵称"%><br />
    <%= f.text_field :usrname %><br />
    <p>
      <%= f.label "email(用于重置密码) "%><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label "密码(at least 4 word)" %><br />
      <%= f.password_field :passwd %>
    </p>
    <p>
      <%= f.label "密码确认" %><br />
      <%= f.password_field :password_confirmation %>
    </p>
  </fieldset>

  <div class="actions">
    <%= f.submit "完成" %>
  </div>
  <% end %>

 <p> <%= link_to '返回', index_path %></p>
</center>

app/views/ranks/show.html.erb
<center>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rank.usrname %>
  <br>
  Pushed puzzles: <%= @rank.num %>
  <br>
  Rigistered at: <%= @rank.created_on %>
  <br>
  Last time she/he pushed puzzles at: <%= (@rank.updated_at).in_time_zone('Beijing') %>
</p>


<p><%= link_to 'Back', index_path %></p>
</center>