config/routes.rb
RailsApp::Application.routes.draw do

  post "usercfg/savecfg"
  get "usercfg/loadcfg"
  get "password_resets/new"
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create", :as => "login"
  get "signup" => "ranks#new", :as => "signup"
  post "signup" => "ranks#create", :as => "signup"
  post "check" => "ranks#check", :as => "check"
  get "index" => "ranks#index", :as => "index"
  get "admin" => "admin#show", :as => "admin"
  post "onlineusr" => "onlineusr#getlist", :as => "onlineusr"
  root :to => 'ranks#index'
  resources :admin
  resources :session
  resources :password_resets
  resources :ranks

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="O-OjdiqJH5PPkb47ZS-sRJSRIfwgMK1m1onPSRf81KM" />
    <meta property="qc:admins" content="65430007547514502116620347546375" />
    <!-- <meta property="wb:webmaster" content="adf1a406c945bc1c" /> -->
    <title>Push Sudoku</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="head">    
      <!-- title bar -->
      <!-- user navgation bar -->
      <div id="user_nav">
        <%= link_to "Home", index_path %> |
        <% if current_user %>
        <strong><%= current_user.usrname %></strong>.
        <%= link_to "退出", logout_path %>
        <% else %>
        <%= link_to "免费注册", signup_path %> |
        <%= link_to "登入", login_path %>
        <% end %>
      </div>

      <h1><em>Push </em>Sudoku</h1>
      <span><h2 class="alt">Practice and Learn, you will Enjoy it!!</h2></span>
    </div>
    
    <div class="container">
      <div class="flash">
        <% if not flash.blank? %>
        <div class="success" >
	  <% flash.each do |name, msg| %>
	  <%= content_tag :div, msg, :id => "flash_#{name}" %>
	  <% end %>
        </div>
        <% end %>
      </div>
      
      <%= yield %>          

      
    </div>
    <div class="footer">
      <center><p> © 2012 Alex-bian, All rights reserved. Contact: bhd.shu@gmail.com </p></center>
    </div>

  </body>
</html>